- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    
- name: install additional packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
