- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/wildfly-{{ WILDFLY_VERSION }}
    dest: /opt/wildfly
    owner: wildfly
    group: wildfly
    force: yes
    state: link
- name: Change owner
  file:
    path: /opt/wildfly-{{ WILDFLY_VERSION }}
    state: directory
    recurse: yes
    owner: wildfly
    group: wildfly
