- name: Create a symbolic link
  ansible.builtin.file:
    src: /opt/wildfly-{{ WILDFLY_VERSION }}
    dest: /opt/wildfly/wildfly-{{ WILDFLY_VERSION }}
    owner: wildfly
    group: wildfly
    force: yes
    state: link
