- name: Enable service wildfly
  ansible.builtin.service:
    name: wildfly
    enabled: yes

- name: Enable firewall
  ansible.posix.firewalld:
    port: "{{item}}"
    permanent: yes
    state: enabled
    zone: public
  with-items:
    - 8080/tcp
    - 9990/tcp
  notify: Reload firewalld
