---
# tasks file for jboss-wildfly

- include: '{{ item }}'
  loop:
    - create_group_user.yml
    - download_wildfly.yml
    - create_link_modify_owner.yml
    - configure_systemd.yml
    - enable_svc_firewall.yml
    - enable_management_console.yml
